# Generated by Django 3.2.6 on 2021-10-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignupForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=150)),
                ('username', models.CharField(max_length=150, null=True)),
                ('password', models.CharField(max_length=150, null=True)),
                ('confirmpassword', models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
