# Generated by Django 3.2.6 on 2021-10-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carName', models.TextField()),
                ('model', models.TextField(blank=True)),
                ('company', models.TextField(blank=True)),
                ('country', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Developers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developerName', models.TextField()),
                ('language', models.TextField(blank=True)),
                ('company', models.TextField(blank=True)),
                ('location', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=256)),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
